# Generated by Django 4.1.3 on 2022-11-22 16:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.CharField(max_length=20, primary_key=True, serialize=False, unique=True)),
                ('numero_telefono', models.CharField(max_length=20, null=None, unique=True)),
                ('nombre', models.CharField(blank=True, max_length=250, null=True)),
                ('apellido', models.CharField(max_length=250, null=True)),
                ('correo', models.EmailField(blank=True, max_length=254, null=True)),
                ('fecha_hora_creacion', models.DateTimeField(auto_now_add=True)),
                ('sms_validacion_creacion', models.BooleanField(default=False)),
                ('sms_validacion_lastlogin', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'usuario',
                'verbose_name_plural': 'usuarios',
            },
        ),
        migrations.CreateModel(
            name='Chat',
            fields=[
                ('id', models.CharField(max_length=20, primary_key=True, serialize=False, unique=True)),
                ('fecha_hora_creacion', models.DateTimeField(auto_now_add=True)),
                ('aceptado', models.CharField(max_length=250, null=True)),
                ('user_desde', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_desde', to='api_chat.user')),
                ('user_hasta', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_hasta', to='api_chat.user')),
            ],
            options={
                'verbose_name': 'chat',
                'verbose_name_plural': 'chats',
            },
        ),
    ]
